-- ============================================================
-- CRAG-Demo — Knowledge Service 真实业务 DDL
-- Schema: knowledge (currentSchema=knowledge, owner crag_knowledge)
-- 通过 Spring sql.init 在默认与 smoke profile 启动时执行；CREATE TABLE IF NOT EXISTS
-- 保证幂等，不清空共享表、不删除 volume。
-- ============================================================

-- KnowledgeBase：知识库，归 Tenant 所有。
CREATE TABLE IF NOT EXISTS knowledge_base (
    knowledge_base_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id           BIGINT NOT NULL,
    name                VARCHAR(255) NOT NULL,
    created_by_user_id  BIGINT NOT NULL,
    status              VARCHAR(32) NOT NULL,
    created_at          TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP NOT NULL DEFAULT NOW(),
    version             BIGINT NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_knowledge_base_tenant ON knowledge_base(tenant_id);

-- Document：上传文档元数据，内容不可变，首版 ingestion_status 固定 PENDING。
CREATE TABLE IF NOT EXISTS document (
    doc_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_base_id   BIGINT NOT NULL,
    tenant_id           BIGINT NOT NULL,
    uploaded_by_user_id BIGINT NOT NULL,
    original_filename   VARCHAR(512) NOT NULL,
    file_type           VARCHAR(32) NOT NULL,
    size_bytes          BIGINT NOT NULL,
    sha256              VARCHAR(64) NOT NULL,
    ingestion_status    VARCHAR(32) NOT NULL,
    operation_version   BIGINT NOT NULL,
    created_at          TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP NOT NULL DEFAULT NOW(),
    version             BIGINT NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_document_kb_tenant ON document(knowledge_base_id, tenant_id);
CREATE INDEX IF NOT EXISTS idx_document_tenant_doc ON document(tenant_id, doc_id);

-- ============================================================
-- router4 摄取投影与失败字段（plan_21/21.3）
-- 幂等迁移：每次启动重复添加，已存在列/索引为 no-op；不修改既有列。
-- failure_message 安全限长由 DAO/Handler 在写入前完成，列存储长度上限与 message column 一致。
-- ============================================================
ALTER TABLE document ADD COLUMN IF NOT EXISTS ingestion_attempt INT;
ALTER TABLE document ADD COLUMN IF NOT EXISTS ingestion_job_id BIGINT;
ALTER TABLE document ADD COLUMN IF NOT EXISTS failure_category VARCHAR(64);
ALTER TABLE document ADD COLUMN IF NOT EXISTS failure_message VARCHAR(512);
ALTER TABLE document ADD COLUMN IF NOT EXISTS started_at TIMESTAMP;
ALTER TABLE document ADD COLUMN IF NOT EXISTS completed_at TIMESTAMP;
ALTER TABLE document ADD COLUMN IF NOT EXISTS next_retry_at TIMESTAMP;
-- ingestion_attempt 在 PENDING 文档创建时固定写入 0，回填旧行为 0 以便 Reconciler 统一扫描。
UPDATE document SET ingestion_attempt = 0 WHERE ingestion_attempt IS NULL;
-- 按 (doc_id, operation_version) 索引支撑版本维度查询/Reconciler（21.5）。
CREATE INDEX IF NOT EXISTS idx_document_doc_version ON document(doc_id, operation_version);

-- FileObject：文件落盘记录，storage_key 仅 Knowledge 内部使用，不跨服务泄漏。
CREATE TABLE IF NOT EXISTS file_object (
    file_object_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_id              BIGINT NOT NULL,
    storage_key         VARCHAR(512) NOT NULL,
    size_bytes          BIGINT NOT NULL,
    sha256              VARCHAR(64) NOT NULL,
    storage_status      VARCHAR(32) NOT NULL,
    created_at          TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP NOT NULL DEFAULT NOW(),
    version             BIGINT NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_file_object_doc ON file_object(doc_id);

-- DOC_UPLOADED 事件 ID 序列；outbox_event.event_id 由 Knowledge producer 取 nextval，
-- 不依赖 Snowflake（plan_18 文件边界不含 crag-id）。
CREATE SEQUENCE IF NOT EXISTS knowledge_event_id_seq START WITH 1 INCREMENT BY 1;

-- ============================================================
-- 可靠事件本地表（crag-event 接入宿主，属 Knowledge 本地 schema）
-- 列结构必须与 crag-event 的 JdbcOutboxEventDao / JdbcProcessedEventDao 保持一致。
-- ============================================================
CREATE TABLE IF NOT EXISTS outbox_event (
  event_id BIGINT NOT NULL PRIMARY KEY,
  event_type VARCHAR(64) NOT NULL,
  producer VARCHAR(64) NOT NULL,
  resource_type VARCHAR(64) NOT NULL,
  resource_id BIGINT NOT NULL,
  operation_version BIGINT NOT NULL,
  payload_version INT NOT NULL,
  payload_json TEXT NOT NULL,
  trace_id VARCHAR(128) NOT NULL,
  occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
  status VARCHAR(16) NOT NULL,
  next_attempt_at TIMESTAMP WITH TIME ZONE,
  attempt_count INT NOT NULL DEFAULT 0,
  last_error_code VARCHAR(48),
  last_error_message VARCHAR(512),
  published_at TIMESTAMP WITH TIME ZONE,
  version BIGINT NOT NULL,
  claimed_by VARCHAR(64),
  claimed_until TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS processed_event (
  consumer_name VARCHAR(64) NOT NULL,
  event_id BIGINT NOT NULL,
  idempotency_key VARCHAR(256) NOT NULL,
  event_type VARCHAR(64) NOT NULL,
  resource_type VARCHAR(64) NOT NULL,
  resource_id BIGINT NOT NULL,
  operation_version BIGINT NOT NULL,
  stream_key VARCHAR(128) NOT NULL,
  stream_record_id VARCHAR(128) NOT NULL,
  first_seen_at TIMESTAMP WITH TIME ZONE NOT NULL,
  processed_at TIMESTAMP WITH TIME ZONE,
  status VARCHAR(16) NOT NULL,
  handler_attempt_count INT NOT NULL DEFAULT 0,
  last_error_code VARCHAR(48),
  last_error_message VARCHAR(512),
  -- De-dupe by idempotency key (event logical identity), not event id: multiple producers share one
  -- Redis stream and each owns an independent outbox event_id sequence, so two different events can
  -- carry the same event id. event_id is a tracked (non-unique) column. (plan_19.7 repair)
  CONSTRAINT pk_processed_event PRIMARY KEY (consumer_name, idempotency_key)
);

-- Idempotent migration (H2- and PostgreSQL-portable): ensure the processed_event primary key is on
-- (consumer_name, idempotency_key) and the redundant unique constraint is gone. Re-applied each
-- startup; on already-current tables this just drops and re-adds the same key.
ALTER TABLE processed_event DROP CONSTRAINT IF EXISTS pk_processed_event;
ALTER TABLE processed_event DROP CONSTRAINT IF EXISTS uq_processed_idempotency;
ALTER TABLE processed_event ADD CONSTRAINT pk_processed_event PRIMARY KEY (consumer_name, idempotency_key);
